name: Backend Elearning CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Update ENV
      env:
        APP_URL: http://188.166.233.97/be-elearning/
        API_DOMAIN: 188.166.233.97/be-elearning
        DB_CONNECTION: mysql
        DB_DATABASE: db_elearning
    - name: Migrate and Seed
      run: php artisan key:generate
    - name: API Cache Clear
      run: php artisan api:cache
    - name: Generate JWT Key
      run : php artisan jwt:secret
    - name: Generate IDE Helper
      run : php artisan ide-helper:generate
